language: node_js
deploy:
  provider: npm
  email: scjosh2@gmail.com
  api_key:
    secure: k+o224lyzxltonHz8EGPkVjzBDL0aIy8vGABqSCAUCb2ghXSmhO4lPvY+k7FTCqROda3d5to4smG3m+45r5aed7S9s8hsFQyrQD6cmtsfakoJTyIMET5WdlmKILjkEhJVEHi+xEkAmr72dEYT4zfp6Iq1U046zhwqMI/YJc4ALg=
  on:
    repo: joshuaferrara/node-csgo
node_js:
    - 'node'
sudo: false
